name: pdune_analysis
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgomp=15.1.0=h767d61c_5
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh145f28c_0
  - python=3.13.7=h2b335a9_100_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_hd72426e_102
  - pip:
      - about-time==4.2.1
      - alive-progress==3.3.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - awkward==2.8.9
      - awkward-cpp==50
      - blosc2==3.9.1
      - boost-histogram==1.6.1
      - cabinetry==0.6.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cramjam==2.11.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.4.0
      - executing==2.2.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - graphemeu==0.7.2
      - hepunits==2.4.1
      - idna==3.10
      - iminuit==2.31.1
      - ipykernel==6.30.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - msgpack==1.1.1
      - multiprocess==0.70.18
      - ndindex==1.10.0
      - nest-asyncio==1.6.0
      - numexpr==2.13.1
      - numpy==2.3.3
      - nvidia-nccl-cu12==2.28.3
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - particle==0.26.0
      - pathos==0.3.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pox==0.3.6
      - ppft==1.7.7
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pyhf==0.7.6
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyunfold==0.5.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.1.0
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - setuptools==80.9.0
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - tables==3.10.2
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uproot==5.6.6
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - xgboost==3.0.5
      - xxhash==3.6.0
